### PR TITLE
cards and responsive ui 

### PR DESCRIPTION
**Pull request by RunTerror**

### CODE REVIEW

**Comment by Bhavikk01** [comment]
@RunTerror 
Try to maintain the consistency in width of all cards or in other words try to give same width to cards with no radius and try to remove unnecessary containers and unused variables in files

**Comment by RunTerror** [comment]
in previous commit everything was almost same and @Roshaen  told me to make changes only in responsiveness also image was not opening but now it is working fine so please let me know is it necessary to change it again

**Comment by Bhavikk01** [comment]
> in previous commit everything was almost same and @Roshaen told me to make changes only in responsiveness also image was not opening but now it is working fine so please let me know is it necessary to change it again

Yes but cards width is not responsive when I run it on my phone. Use the variable which you declared and initialized with media query. Also try to remove unnecessary containers and all that.

**Comment by RunTerror** [comment]
ya i know the width of second card is less when a big device is used but when i make it responsive that cards looks ugly because all its content does not align and also the picture background shows with some remaining white and black border of container

**Comment by RunTerror** [comment]
i will solve it please suggest me some solution

**Comment by Bhavikk01** [comment]
> i will solve it please suggest me some solution

Try giving image in background of a container rather then child in sizedbox. It will fix the issue of some remaining white and black border. And set the fontSize properly to maintain the alignment of text

**Comment by RunTerror** [comment]
Screenshot_1678426400
i have used a row in which i have wrapped image with sizedbox to fit in it and for text content i have used a column and that column i have wrapped with fittedbox so that the height of the overall row should not go out but now problem here is how can i fix the fontsize dynamically so that uses the space right

**Comment by RunTerror** [comment]
Screenshot_1678440929
Screenshot_1678440942

this time i have cheked it on multiple emulator this is working fine

**Comment by Bhavikk01** [comment]
@RunTerror 
Yes now its working fine.

**Pull request merged**
