### PR TITLE
Create LoginpagedesignSowmiya.html

### LINKED ISSUE #34: Design Screen for Signup Page
Creating design screens using Figma, the Final design which is confirmed by the team can be used for building flutter UI #5 

- Should upload screenshots
- Should paste the Figma link

### PR DESCRIPTION
**Pull request by sowmiya-venkatesan**
# Description

Created design screens using Figma, the Final design which is confirmed by the team can be used for building flutter UI #5

Fixes #34

## Type of change
- [x] Enhancement of UI design screens
- [x]  New feature (non-breaking change which adds functionality)

## Checklist

- [x] My design follows the style guidelines of this project
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works

## Screenshots
 **1. Dark mode**
Dark Mode - Clueless login

 **2. Light mode**
Light Mode - Clueless login

## Figma Link
[https://www.figma.com/file/P4uC0jmYgUnd10UmANnh7O/Clueless-login?node-id=0%3A1](url)

### CODE REVIEW

**Comment by Roshaen** [comment]
You can create a new folder and add the frontend files there
It can't be added in lib folder

**Comment by sowmiya-venkatesan** [comment]
> You can create a new folder and add the frontend files there It can't be added in lib folder

Yes done, with it

**Comment by sowmiya-venkatesan** [comment]
> You can create a new folder and add the frontend files here It can't be added in the lib folder

Completed it, @Roshaen 
Also, you can refer Figma file - https://www.figma.com/file/P4uC0jmYgUnd10UmANnh7O/Clueless-login?node-id=1%3A167

**Comment by Debajyoti14** [comment]
@sowmiya-venkatesan You can't put Figma designs and png files into the folder. As we want Flutter code to be integrated into the app. If you know how to build the UI with Flutter & Dart, you can do it, else I can add your designs in the issues sections so that others can help build the nice design you provided if you permit.

**Comment by sowmiya-venkatesan** [comment]
> @sowmiya-venkatesan You can't put Figma designs and png files into the folder. As we want Flutter code to be integrated into the app. If you know how to build the UI with Flutter & Dart, you can do it, else I can add your designs in the issues sections so that others can help build the nice design you provided if you permit.

@Debajyoti14, I've mentioned clearly in the description, that the issue is for only Figma designs and yes, you can add this design to the issue sections so those flutter developers can build it.

**Comment by Debajyoti14** [comment]
@sowmiya-venkatesan Ok thanks,
We will add your figma design in the issue

**Comment by sowmiya-venkatesan** [comment]
> @sowmiya-venkatesan Ok thanks, We will add your figma design in the issue

Please, Merge this PR#37, as it is relevant to this issue, if not please close it, Thanks!

**Comment by Debajyoti14** [comment]
@sowmiya-venkatesan Closing this but will add your designs in the issue

**Pull request closed without merging**
