### PR TITLE
Added Profile Page 2

### PR DESCRIPTION
**Pull request by chandansgowda**
Ref - #62 

dark
light

### CODE REVIEW

**Comment by Roshaen** [comment]
This part is overflowed
please fix this @chandansgowda 
photo_2022-12-05_23-20-45

**Comment by chandansgowda** [comment]
Hey @Roshaen 
May I know in which device dimensions it's overflowing??

**Comment by chandansgowda** [comment]
Hey @Roshaen 
I have resolved the error now. Please check.

**Comment by chandansgowda** [comment]
Hey @Roshaen 
Thanks for reviewing and merging the PR.
My Profile URL - https://www.clueless.tech/profile/41890434

**Pull request merged**
