### PR TITLE
Closes #122 [`Refactor Codebase`]

### LINKED ISSUE #122: [Refactor codebase]
1. Use const for constant constructors
2. fix the naming convention of files and folders
3. remove unused files
4. Making code short where possible

### PR DESCRIPTION
**Pull request by sarkartanmay393**
### Summary

**Things I'd to do:**
1. add `const`
2. naming conventions
3. removed unused code
4. updated deprecated code

**Affected Files:**
image

### CODE REVIEW

**Comment by Bhavikk01** [comment]
@sarkartanmay393 
Please do the same for remaining files and also try to remove the deprecated attributes and implement their alternative thing.
You can see the remaining from DartAnalysis tool

**Comment by sarkartanmay393** [comment]
@Bhavikk01 I updated the whole code.
Btw Bhavik, are you one of the maintainers here?

**Comment by sarkartanmay393** [comment]
@Roshaen Can you review and pass it down tonight?

**Comment by Bhavikk01** [comment]
> @Bhavikk01 I updated the whole code. Btw Bhavik, are you one of the maintainers here?

Yes I am also one of the maintainer for flutter-ui-components

**Comment by sarkartanmay393** [comment]
> > @Bhavikk01 I updated the whole code. Btw Bhavik, are you one of the maintainers here?
> 
> Yes I am also one of the maintainer for flutter-ui-components

Then you can review it to merge.

**Pull request merged**
