### PR TITLE
All alert design code will come via this branch , Creating Pull Request for the same

### PR DESCRIPTION
**Pull request by Akashsri3bi**
This contains the first alert design code in flutter , All other alert design code will come though this PR only . Please review it once and if there are any changes do tell. Since Alert Contains a lot of designs and there is one issue so keeping it in one PR or branch will be good to go @Roshaen please review

### CODE REVIEW

**Comment by Roshaen** [comment]
Sure
Will review it

**Comment by Roshaen** [comment]
Make this alert disappear when clicked on the cross button
Also, add  fade out animation @Akashsri3bi

**Comment by Akashsri3bi** [comment]
> Make this alert disappear when clicked on the cross button Also, add fade out animation @Akashsri3bi

Disappear I mean these are UI components ?they should disappear on click then how we will show a catalog

**Comment by Akashsri3bi** [comment]
@Roshaen @Debajyoti14 Alert for light is complete please review and merge

**Comment by Roshaen** [comment]
Resolve the merge conflict @Akashsri3bi

**Comment by Akashsri3bi** [comment]
@Roshaen Done

**Pull request merged**
