### PR TITLE
Added Search Bar #4

### LINKED ISSUE #4: Create searchbar
Implement a searchbar to find components

### PR DESCRIPTION
**Pull request by Perumallpardhiv**
# Description

Added Functionality for SearchBar

Fixes #4 

Added a Feature : Functionality of SearchBar

https://user-images.githubusercontent.com/96647299/196417082-62ac724d-de2c-4159-a799-5622992f93a2.mp4

### CODE REVIEW

**Comment by Perumallpardhiv** [comment]
@Roshaen 
My ClueLess profile : https://www.clueless.tech/profile/admin/96647299

**Comment by Perumallpardhiv** [comment]
@nikhil25803 
Is did counted in my Clueless profile ??
My ClueLess profile : https://www.clueless.tech/profile/admin/96647299

**Comment by nikhil25803** [comment]
Hey @Perumallpardhiv, it will be shown on the leaderboard once it gets updated. In the clueless profile, you need to add manually(if you want).

**Comment by Perumallpardhiv** [comment]
> Hey @Perumallpardhiv, it will be shown on the leaderboard once it gets updated. In the clueless profile, you need to add manually(if you want).

@nikhil25803 
Thanks for your reply
I have successfully completed 4 pr's where all are merged with master branch(latest pr merged 2 days ago) but, in leaderboard only 3 pr's counted 
Can I know the reason ?

Once again Thank you

**Comment by nikhil25803** [comment]
@Perumallpardhiv 
The 4th one will get added once the leaderboard gets updated.

**Comment by Perumallpardhiv** [comment]
> @Perumallpardhiv The 4th one will get added once the leaderboard gets updated.

Ok sir
Thank you

**Comment by Perumallpardhiv** [comment]
@nikhil25803 
Sir, can I know generally how much time it will take to update Leaderboard ?

**Comment by nikhil25803** [comment]
About 24HRS @Perumallpardhiv

**Comment by Perumallpardhiv** [comment]
> It is updated now @Perumallpardhiv, you may check.

@nikhil25803 
Still it is showing that only 3 pr's merged from my profile

**Comment by nikhil25803** [comment]
Yes, because only 3 of  your PR has been merged @Perumallpardhiv

**Comment by Perumallpardhiv** [comment]
> Yes, because only 3 of your PR has been merged @Perumallpardhiv

4 pr's merged can I send the photo here ?

**Comment by nikhil25803** [comment]
Yes, please. If so, i'll look into this.

**Comment by Perumallpardhiv** [comment]
This are the 4 pr's of clueless community

image

**Comment by nikhil25803** [comment]
Oh, one merged PR missing the `Oktoberfest-accepted` tag. That's why it is not reflected on the leaderboard. It will get updated by evening today, don't worry :)

**Comment by Perumallpardhiv** [comment]
> Oh, one merged PR missing the `hacktoberfest-accepted` tag. That's why it is not reflected on the leaderboard. It will get updated by evening today, don't worry :)

Still it's not updated sir

**Pull request merged**
