### PR TITLE
Naviagtion Bar

### PR DESCRIPTION
**Pull request by Uttkarsh-raj**

### CODE REVIEW

**Comment by ashdude1401** [comment]
Congratulations, @Uttkarsh-raj your pr has been merged .Don't forget to star the repo . Untill your next pr, keep coding and  keep contributing.

**Comment by Uttkarsh-raj** [comment]
@ashdude1401 Thank you for assigning this to me....had a great learning experience....

**Comment by Uttkarsh-raj** [comment]
hey @ashdude1401 can you please add the required tags/labels to this merged pr since it is not showing as my jwoc contribution on the leaderboard page..

**Comment by ashdude1401** [comment]
sorry ,I forgot to lable it .Let see what I can see

**Comment by ashdude1401** [comment]
@Uttkarsh-raj  you have again send a pull request . I have added all the required tags.

**Pull request merged**
